format = """
[](#e0af68)\
[ 󰇥 ](bg:#e0af68 fg:#1a1b26)\
[](bg:#769ff0 fg:#e0af68)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](#394260)\
\n$character"""

# follow_symlinks = false

[character]
success_symbol = '[](bold #9ece6a) '
error_symbol = '[✘](bold #f7768e) '
vimcmd_symbol = '[](bold #9ece6a) '

[directory]
style = "fg:#1A1B26 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "󰋜 "

[git_branch]
symbol = "󰘬"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = true
time_format = '%I:%M %p'
style = "bg:#1d2230"
format = '[[   $time ](fg:#a0a9cb bg:#1d2230)]($style)'
